base: core18
name: mysql-workbench-community
title: MySQL Workbench
version: 8.0.19
summary: MySQL Workbench - a visual database modeling, administration and queuing tool
description: |
  MySQL Workbench is a modeling tool that allow to design
  and generate MySQL databases graphically. It also has administration
  and query development modules where you can manage MySQL server instances
  and execute SQL queries.
type: app
grade: devel
confinement: strict
license: GPL-2.0
icon: mysql-workbench.png
architectures:
  - build-on: amd64

apps:
  mysql-workbench-community:
    command: desktop-launch $SNAP/usr/bin/mysql-workbench
    desktop: usr/share/applications/mysql-workbench.desktop
    extensions:
      - gnome-3-28
    plugs:
      - home
      - opengl
      - network
      - ssh-keys
      - password-manager-service
    environment:
      PYTHONPATH: $SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib/python2.7/:/$SNAP/usr/lib/python2.7/plat-x86_64-linux-gnu/:$PYTHONPATH
      PYTHONHOME: $SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib/python2.7/:/$SNAP/usr/lib/python2.7/plat-x86_64-linux-gnu/:$PYTHONHOME
      PROJSO: $SNAP/usr/lib/x86_64-linux-gnu/libproj.so
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      WB_DEST_DIR: $SNAP

parts:
  config:
    plugin: nil
    override-pull: |
      echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-tools" > /etc/apt/sources.list.d/mysql-tools.list
      apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 8C718D3B5072E1F5
      apt update

  install:
    plugin: nil
    after: [config]
    stage-packages:
      - mysql-workbench-community
      - libcanberra-gtk3-module
      - libproj12
      - libproj-dev
      - python2.7
      - lsb-release
      - libc-bin

  fix-icon:
    plugin: nil
    override-build:
      sed -i 's|Icon=mysql-workbench|Icon=/usr/share/icons/hicolor/128x128/apps/mysql-workbench.png|' $SNAPCRAFT_STAGE/usr/share/applications/mysql-workbench.desktop
    after: [install]
